---

- import_tasks: clone_repository.yml

- import_tasks: variables.yml

- import_tasks: link_files.yml

- include_tasks: link_directory.yml
  with_items: "{{ dotfiles.files | selectattr('isdir') }}"
  loop_control:
    loop_var: dotfiles_directory
    label: "{{ dotfiles_directory.path }}"
