---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: dotfiles
    image: geerlingguy/docker-ubuntu2004-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      dotfiles:
        dotfiles_repository: 'https://github.com/acimadamore/dotfiles'

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
